language: en-US
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions: []
  path_filters: []
  path_instructions: []
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    drafts: false
    base_branches: []
  tools:
    biome:
      enabled: true
    gitleaks:
      enabled: true
    github-checks:
      enabled: true
      timeout: 5
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    languagetool:
      enabled: true
      enabled_only: false
      level: default
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
    checkov:
      enabled: true
    semgrep:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  opt_in: true
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []
  pull_requests:
    scope: auto
